### ISSUE TITLE
Extend configuration to capture image used for runtime environment

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#579]
**Is your feature request related to a problem? Please describe.**

I, as Thoth user, would like to specify container image I use to run my application so that Thoth can recommend specifically for my container image.

**Describe the solution you'd like**

Besides a generic configuration for OS and Python, it would be great to add an ability to specify the container image used as a runtime environment. This way, the thoth can use its pre-aggregated knowledge about the container image used (based on the container image analyses it does on the background) when creating recommendations. An example can be information about native dependencies and their versions present in the container image (e.g. glibc version). 

An example configuration can be:

```yaml
host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: rhel:8
    operating_system:
      name: rhel
      version: "8"
    python_version: "3.6"
    recommendation_type: latest
    image: quay.io/thoth-station/adviser:200e9f2fb851
```

This capability can be used together with Amun. Amun would build container images for users (having required native dependencies baked in it, for example mkl, glibc), Thoth would analyze these container images and automatically sync container image analyses to Thoth's knowledge base. The information synced can be used in adviser's recommendation engine as users will provide this info in their Thoth's configuration file (or this information can be provdided directly in the container images built in an environment variable and Thamos' autodetection mechanism can assign the container image in the config file).
