### ISSUE TITLE
Create method to add new runtime environment to thoth config

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thamos#739]
**Is your feature request related to a problem? Please describe.**
Related-To: https://github.com/thoth-station/jupyterlab-requirements/issues/116

**Describe the solution you'd like**
Have a method in thamos library that receives a dictionary relative to runtime environment containing required parameters:

```
  - name: {kernel_name}
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest
```

and add to thoth config list of runtime environments.

- Having a `force` optional parameter also in order to override the existing runtime environment with same name.

- Having a schema check to verify the dictionary inserted contains all mandatory fileds required by thoth.

**Describe alternatives you've considered**

**Additional context**
