### ISSUE TITLE
Maintain initial format after saving thoth config file

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thamos#747]
**Is your feature request related to a problem? Please describe.**
After adding new runtime environment and saving file for `.thoth.yaml`, the yaml style is lost. It would be nice to keep it, if possible. 

initial:
```
host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: rhel:8
    operating_system:
      name: rhel
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

managers:
  - name: pipfile-requirements
  - name: update
    configuration:
      labels: [bot]
  - name: info
  - name: version
    configuration:
      maintainers:
        - goern
        - fridex
        - sesheta
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true

```

run:
```
from thamos.config import _Configuration

configuration = _Configuration()
runtime_environment = {
    "name": "test",
    "operating_system": {
        "name": "rhel",
        "version": "8"
    },
    "python_version": "3.8",
    "recommendation_type": "latest"
}
configuration.set_runtime_environment(runtime_environment=runtime_environment, force=False)
configuration.save_config()

```

updated:
```
host: khemenu.thoth-station.ninja
managers:
- name: pipfile-requirements
- configuration:
    labels:
    - bot
  name: update
- name: info
- configuration:
    assignees:
    - sesheta
    changelog_file: true
    labels:
    - bot
    maintainers:
    - goern
    - fridex
    - sesheta
  name: version
requirements_format: pipenv
runtime_environments:
- name: rhel:8
  operating_system:
    name: rhel
    version: '8'
  python_version: '3.8'
  recommendation_type: latest
- name: test
  operating_system:
    name: rhel
    version: '8'
  python_version: '3.8'
  recommendation_type: latest
tls_verify: false

```
**Describe the solution you'd like**
Have a mechanism to keep style when saving updated `.thoth.yaml`.

**Describe alternatives you've considered**

**Additional context**
