### ISSUE TITLE
Extend Thamos with a new flag to get the base image recommended

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thamos#910]
**Is your feature request related to a problem? Please describe.**
See: https://github.com/AICoE/recommend-base-image-tutorial/issues/1

**Describe the solution you'd like**
Extend Thamos with a new flag to get the base image recommended and provide it to the user.

**Describe alternatives you've considered**

**Additional context**

**Comment by pacospace** [comment]
this is required for https://github.com/AICoE/recommend-base-image-tutorial/issues/1#issuecomment-934150583

**Comment by fridex** [comment]
I don't see any blockers to have this implemented.

**Comment by fridex** [comment]
It might be good to provide a generic mechanism for this in `advised_manifest_changes` so we can generalize the feature. Something like (rough design just to show the functionality):

```yaml
advised_manifest_changes:
 - file: .thoth.yaml  # File that should be patched (can be also a buildconfig or so).
   patch:
     add: ...
```
